homework 11
Kiris15/iosSchool pull request #10
Opened 2023-04-30 16:26 UTC by Kiris15

2023-05-01 06:54 UTC, vaganova-ann requested changes
А где будет выполняться запрос данных профиля с сервера?

2023-05-01 06:54 UTC, vaganova-ann commented on iosShcool/ApiClient/ProfileApiClient.swift
> +    let url = NetworkConstants.URLStrings.nanoPost + "/v1/posts/{profileId}"
profileId это параметр, который надо передавать в запрос, чтобы получить данные пользователя

2023-05-01 06:54 UTC, vaganova-ann commented on iosShcool/AppDelegate.swift
> +//        assembly.storageManager.cleanKeychainIfNeeded()
почему закомментировала?

2023-05-01 06:54 UTC, vaganova-ann commented on iosShcool/Auth/AuthViewController.swift
> +        UserDefaults.standard.set(Date(), forKey: "lastEntranceDate")
все действия с UserDefaults выполняем в StorageManager по аналогии с действиями с кейчейном

2023-05-01 06:54 UTC, vaganova-ann commented on iosShcool/Registration/RegistrationViewController.swift
> +        UserDefaults.standard.set(Date(), forKey: "lastEntranceDate")
надо сохранять дату залогина в AppCoordinator, чтобы дублировать код

2023-05-01 06:54 UTC, vaganova-ann commented on iosShcool/Services/StorageManager.swift
> +      UserDefaults.standard.removePersistentDomain(forName: appDomain)
UserDefaults очищается автоматически при удалении приложения, дополнительные действия для этого совершать не нужно

2023-05-02 14:13 UTC, Kiris15 commented on iosShcool/AppDelegate.swift
> +//        assembly.storageManager.cleanKeychainIfNeeded()
закомментила, чтобы проверить сохраняются ли данные в keychain. Если оставить эту строчку, то keychain чистится при каждом запуске.

2023-05-03 02:09 UTC, vaganova-ann commented on iosShcool/ApiClient/ApiClient.swift
> +        do {
а зачем это?

2023-05-03 02:19 UTC, vaganova-ann requested changes

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/ApiClient/ApiClient.swift
> +          let decodedValue: ResponseModel = try JSONDecoder().decode(ResponseModel.self, from: data)
а зачем здесь do catch?

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/AppDelegate.swift
> +//        assembly.storageManager.cleanKeychainIfNeeded()
keychain не должен чиститься при каждом запуске, только после удаления приложения и повторной установке, надо найти баг и пофиксить

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/AppCoordinator.swift
> +      self?.assembly.apiClient.getProfile(profileId: userId) { result in
потеряла weak self

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/AppCoordinator.swift
> +    let coordinator = assembly.authCoordinator(onLoginSuccess:  { [weak self] userId in
лишний пробел перед скобкой {

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/Cabinet/CabinetView.swift
> +        let storageManager = StorageManagerImp()
не инициализируем менеджеры где угодно, передаем его из ассемблайки во вью контроллер, а потом username передаем во вью с помощью CabinetViewData

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/Cabinet/SubViews/TextCell/TextCell.swift
> +      let storageManager = StorageManagerImp()
не инициализируем менеджеры где угодно, передаем его из ассемблайки во вью контроллер, а потом data передаем во вью с помощью CabinetViewDatam, а из даты во вью модель ячейки

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/Services/StorageManager.swift
> +        return "Логин пользователя"
я бы возвращала nil, чтобы метод был более универсальный, а потом уже, во вью модели кабинета или ячеек кабинета заменяла бы nil на конкретный плейсхолдер, то есть каждый модуль будет отвечать за свои плейсхолдеры

2023-05-03 02:19 UTC, vaganova-ann commented on iosShcool/Services/StorageManager.swift
> +    UserDefaults.standard.set(currentDate, forKey: "DateOfEntrance")
ключ DateOfEntrance можно добавить в StorageManagerKey

2023-05-03 12:33 UTC, Kiris15 commented on iosShcool/ApiClient/ApiClient.swift
> +          let decodedValue: ResponseModel = try JSONDecoder().decode(ResponseModel.self, from: data)
Я забыла вернуть наш изначальный вариант обратно. Могу вернуть. Это делалось, чтобы поймать ошибку: у меня не работал запрос профиля, не могла понять почему и чтобы не гадать мне подсказали такую обертку. С ней проблема пишется в логи - что конкретно не работает, так и выясняла в чем была проблема

2023-05-04 02:37 UTC, vaganova-ann requested changes

2023-05-04 02:37 UTC, vaganova-ann commented on iosShcool/Services/StorageManager.swift
> +    case dateOfEntrance
а теперь в менеджере заменить везде
UserDefaults.standard.string(forKey: "DateOfEntrance")
на 
UserDefaults.standard.string(forKey: StorageManagerKey.dateOfEntrance.rawValue)

2023-05-04 02:37 UTC, vaganova-ann commented on iosShcool/Cabinet/CabinetViewController.swift
> +    storageManager.cleanKeychainIfNeeded()
нашла у тебя баг в StorageManagerImp
в cleanKeychainIfNeeded на 33 строчке нужно вызывать saveFirstLaunch вместо notFirstLaunch, тогда у тебя не будет очищаться кейчейн при каждом входе, только при самой первой загрузке приложения
если поправить, то тогда вызов здесь функции cleanKeychainIfNeeded бессмысленный, тк он не будет очищать кейчейн

2023-05-04 13:49 UTC, vaganova-ann commented on iosShcool/Services/StorageManager.swift
> +    UserDefaults.standard.set(currentDate, forKey: "dateOfEntrance")
здесь тоже вместо "dateOfEntrance" надо использовать StorageManagerKey.dateOfEntrance.rawValue

2023-05-04 13:50 UTC, vaganova-ann requested changes

2023-05-04 13:50 UTC, vaganova-ann commented on iosShcool/Services/StorageManager.swift
> +    UserDefaults.standard.set(currentDate, forKey: "dateOfEntrance")
здесь тоже вместо "dateOfEntrance" надо использовать StorageManagerKey.dateOfEntrance.rawValue

2023-05-05 03:04 UTC, vaganova-ann approved these changes

2023-05-05 05:25 UTC, merged